### ISSUE TITLE
Fix OIDC On FOSSA

### ISSUE THREAD

**Issue by ALRubinger** [block/example-java-kotlin-maven-multimodule#11]
And would you please document how to set up OIDC for a new project and how that gets applied to the project as well? That part would be great in a Google Doc and we can port it into the Open Source Program Google Doc when we have that at the ready.

Failures: 
https://github.com/block/example-java-kotlin-maven-multimodule/actions/runs/11374112067/job/31642132638

**Comment by finn-block** [comment]
I think the failure here is because the rule only allows on TBD54566975 repos. The plan with using AWS Secrets Manager to make FOSSA work on external PRs never really ended up working, so I'm going to go ahead and put the FOSSA API key in the org-level github secrets. This should make it easier for everyone.

**Comment by ALRubinger** [comment]
@finn-block At least near term that sounds great to me - we can do MVP of the program this way and always tighten things up later. Thanks!

**Comment by finn-block** [comment]
This is now resolved
